# Generated by Django 4.0.3 on 2022-04-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_roots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('Title', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=3)),
                ('About', models.TextField()),
                ('EffectiveDate', models.DateTimeField(auto_now_add=True)),
                ('TerminationDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('Title', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=3)),
                ('About', models.TextField()),
                ('EffectiveDate', models.DateTimeField(auto_now_add=True)),
                ('TerminationDate', models.DateTimeField()),
            ],
        ),
    ]
